### PR TITLE
bring in directory listing

### LINKED ISSUE #19: Move directory listing component into ion
It can be a top level component we expose as well.

One thing missing from our directory listing component in the nteract/nteract monorepo is the "Grouped" directory listing component. I'd love to see that over here as an option too.

### PR DESCRIPTION
**Pull request by alexandercbooth**
Closes #19.
- [x] add grouped directory listing
- [ ] remove `@nteract/directory-listing` from the monorepo -- I am guessing this might have to wait until publishing?

### CODE REVIEW

**Comment by alexandercbooth** [comment]
Odd, I think I updated that snapshot locally. Might have to do a `git clean -xfd ` 🤔

**Comment by alexandercbooth** [comment]
Whoops, hadn't rebased after that circle PR 😅

**Comment by alexandercbooth** [comment]
Also, added in the
```jsx
import { Card } from "@nteract/ion";
```
for each component since the directory listing ones included it, but I don't know if we want them here (I guess I am thinking maybe not?) 🤔

**Comment by rgbkrk** [comment]
It's ok to make the directory listing in the monorepo rely on this package once ready.

**Comment by alexandercbooth** [comment]
Grr, still not the right updated snapshot. I am not sure what is happening here. Maybe I didn't setup the jestcache correctly on circle?

**Comment by rgbkrk** [comment]
I have to admit, the `<Name />` component is super weird seeing it in these docs. I wonder if it's more similar to having a stable suite of typography bits to use. 🤔

**Comment by rgbkrk** [comment]
I'm beginning to think we should only do new component development in here so we're not fractured between here and the monorepo. We should make a release with some components we're going to start incorporating for use in the monorepo. 🤔

**Comment by alexandercbooth** [comment]
>I'm beginning to think we should only do new component development in here so we're not fractured between here and the monorepo

Good thinking! That should keep ion more cohesive overall.

Closing this 😄

**Pull request closed without merging**
